name: gs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - cudatoolkit=11.7
  - pip:
    - torch==1.13.0
    - torchvision==0.14.0
    - diffusers==0.11.1
    - transformers==4.34.0
    - pytorch_lightning==2.2.1
    - huggingface_hub==0.22.2
    - datasets==2.18.0
    - timm==0.5.4
    - kornia==0.6.4
    - einops==0.4.1
    - open_clip_torch==2.20.0
    - numpy==1.24.4
    - scipy==1.13.0
    - Pillow==10.3.0
    - albumentations==1.4.3
    - scikit-image
    - matplotlib==3.7.5
    - pycryptodome==3.20.0
    - omegaconf==2.3.0
    - PyYAML==6.0.1
    - regex==2023.12.25
    - ftfy==6.2.0
    - tqdm==4.66.2
    - Requests==2.31.0
    - more_itertools==10.2.0
    - natsort==8.4.0
    - typing_extensions==4.11.0
    - academictorrents==2.3.3
